--
-- 0000: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- 0000: NOTE: You must NOT make changes to this script in an editor, it
-- 0000: is automatically generated by the database-generator.sql script
-- 0000: the output from that script is this script.
-- 0000: DATE: 2024-10-05 15:47:05.953409+01
-- 0000: TABLE: publisher: 1, magazine: 1, issue: 1, page: 40, page_item_type: 8, description_type: 3, page_item: 21
-- 0000: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- 
-- 0010: Create a new schema for the data
  DROP SCHEMA IF EXISTS tmap_v0 CASCADE;
  CREATE SCHEMA tmap_v0;
-- 0011: Add in a function to return table and row counts
  CREATE OR REPLACE FUNCTION tmap_v0.get_table_row_counts_v0() RETURNS TEXT AS $$
  DECLARE
    -- This function is used to get a count from all the tables in the schema
    table_record TEXT;
    row_count TEXT;
    result_string TEXT := '';
  BEGIN
    FOR table_record IN
      SELECT table_name AS name
      FROM information_schema.tables
      WHERE table_schema = 'tmap_v0'
      AND table_type = 'BASE TABLE'
    LOOP
      EXECUTE format('SELECT COUNT(*)::text FROM %I.%I', 'tmap_v0', table_record)
      INTO row_count;
      result_string := result_string || table_record || ': ' || row_count || ', ';
    END LOOP;
    result_string := rtrim(result_string, ', ');
    RETURN result_string;
  END;
  $$ LANGUAGE plpgsql;
-- 0020: Create a table for publishers
  CREATE TABLE tmap_v0.publisher (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    key TEXT NOT NULL
  );

-- 0030: Insert publishers
  INSERT INTO tmap_v0.publisher (name, key)
  VALUES (
    'Bar Hill Community Association', 
    'BHCA'
  );
-- 0040: Create a table for magazines
  CREATE TABLE tmap_v0.magazine (
    id SERIAL PRIMARY KEY,
    publisher_id INTEGER NOT NULL,
    name text NOT NULL,
    key text NOT NULL,
    copyright BOOLEAN DEFAULT TRUE,
    default_x INTEGER NOT NULL,
    default_y INTEGER NOT NULL
  );

-- 0050: Insert magazines
  INSERT INTO tmap_v0.magazine (name, key, copyright, publisher_id, default_x, default_y)
  VALUES ('Bar Hill News', 'BHN', false, (SELECT id FROM tmap_v0.publisher WHERE key = 'BHCA'), 2, 2);
-- 0040: Create a table for magazine issues
  CREATE TABLE tmap_v0.issue (
    id SERIAL PRIMARY KEY,
    magazine_id INTEGER NOT NULL,
    date DATE NOT NULL,
    reference TEXT NOT NULL,
    name text NOT NULL,
    key text NOT NULL,
    default_x INTEGER,
    default_y INTEGER
  );

-- 0070: Insert issues
  INSERT INTO tmap_v0.issue (magazine_id, date, reference, name, key, default_x, default_y)
  VALUES (
    (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN'), 
    '2024-10-01'::DATE, 
    '', 
    'Bar Hill News 202410 October 2024 Issue 661', 
    '202410', 
    null, 
    null
  );
-- 0080: Create a table for magazine issue pages
  CREATE TABLE tmap_v0.page (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER NOT NULL,
    page_number INTEGER NOT NULL,
    key TEXT NOT NULL,
    x INTEGER,
    y INTEGER
  );

-- 0080: Insert pages
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    1, 
    'P1', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    10, 
    'P10', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    11, 
    'P11', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    12, 
    'P12', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    13, 
    'P13', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    14, 
    'P14', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    15, 
    'P15', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    16, 
    'P16', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    17, 
    'P17', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    18, 
    'P18', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    19, 
    'P19', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    2, 
    'P2', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    20, 
    'P20', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    21, 
    'P21', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    22, 
    'P22', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    23, 
    'P23', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    24, 
    'P24', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    25, 
    'P25', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    26, 
    'P26', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    27, 
    'P27', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    28, 
    'P28', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    29, 
    'P29', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    3, 
    'P3', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    30, 
    'P30', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    31, 
    'P31', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    32, 
    'P32', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    33, 
    'P33', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    34, 
    'P34', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    35, 
    'P35', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    36, 
    'P36', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    37, 
    'P37', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    38, 
    'P38', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    39, 
    'P39', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    4, 
    'P4', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    40, 
    'P40', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    5, 
    'P5', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    6, 
    'P6', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    7, 
    'P7', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    8, 
    'P8', 
    2, 
    20
  );
  INSERT INTO tmap_v0.page (issue_id, page_number, key, x, y)
  VALUES (
    (SELECT id FROM tmap_v0.issue WHERE key = '202410' AND magazine_id = (SELECT id FROM tmap_v0.magazine WHERE key = 'BHN')), 
    9, 
    'P9', 
    2, 
    20
  );
-- 0090: Create a table for page item types
  CREATE TABLE tmap_v0.page_item_type(
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );

-- 0100: Insert page item types
  INSERT INTO tmap_v0.page_item_type(name)
  VALUES (
    'advert'
  );
  INSERT INTO tmap_v0.page_item_type(name)
  VALUES (
    'article'
  );
  INSERT INTO tmap_v0.page_item_type(name)
  VALUES (
    'contents'
  );
  INSERT INTO tmap_v0.page_item_type(name)
  VALUES (
    'footer'
  );
  INSERT INTO tmap_v0.page_item_type(name)
  VALUES (
    'header'
  );
  INSERT INTO tmap_v0.page_item_type(name)
  VALUES (
    'illustration'
  );
  INSERT INTO tmap_v0.page_item_type(name)
  VALUES (
    'photo'
  );
  INSERT INTO tmap_v0.page_item_type(name)
  VALUES (
    'reader content'
  );
-- 0110: Create a table for description types
  CREATE TABLE tmap_v0.description_type(
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );

-- 0120: Insert description types
  INSERT INTO tmap_v0.description_type(name)
  VALUES (
    'detail'
  );
  INSERT INTO tmap_v0.description_type(name)
  VALUES (
    'exact'
  );
  INSERT INTO tmap_v0.description_type(name)
  VALUES (
    'summary'
  );
-- 0130: Create a table for page items
  CREATE TABLE tmap_v0.page_item (
    id SERIAL PRIMARY KEY,
    page_id INTEGER NOT NULL,
    order_by INTEGER NOT NULL DEFAULT 1,
    key TEXT NOT NULL,
    type_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    description_type_id INTEGER NOT NULL,
    x_start INTEGER NOT NULL,
    y_start INTEGER NOT NULL,
    spanWidth INTEGER NOT NULL DEFAULT -1,
    spanHeight INTEGER NOT NULL DEFAULT -1
  );

-- 0140: Insert page items
 
-- 0150: Page 0001 item 01
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 1
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  1, -- order_by
  'I1', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'header'), -- type_id
  'Front Page Cover', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'summary'), -- description_type_id
  'Bar Hill News cover page header with the issue, month, and logos', -- description
  0, -- x_start
  0, -- y_start
  2, -- spanWidth
  3 -- spanHeight
);
 
-- 0150: Page 0001 item 02
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 1
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  2, -- order_by
  'I2', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'contents'), -- type_id
  'A short (4) list of key articles highlighted by the editor inside this month''s issue', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Letters Page 4, The Library Presents Page 6, Memorial Garden Page 32, and Bar Hill Cricket Club Page 33', -- description
  0, -- x_start
  17, -- y_start
  1, -- spanWidth
  3 -- spanHeight
);
 
-- 0150: Page 0001 item 02
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 1
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  2, -- order_by
  'I2', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'illustration'), -- type_id
  'Front Page Background Image', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'summary'), -- description_type_id
  'A halloween-style illustration with a tree, bats, and pumpkin', -- description
  0, -- x_start
  4, -- y_start
  2, -- spanWidth
  15 -- spanHeight
);
 
-- 0150: Page 0001 item 03
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 1
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  3, -- order_by
  'I3', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'article'), -- type_id
  'Bus Franchising Consultation', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Cambridgeshire and Peterborough Combined Authority have started a review of how bus services are operated. As part of this review they are holding a formal consultation on "Bus Franchising". The results of this consultation will feed into the decision by the Mayor on how best to improve services for all. More information on the consultation is available via the website; https://cpca-yourvoice.co.uk/bus-franchising-consultation/ This includes a detailed proposal, forms to submit your views online as well as printable versions for completing offline (and posting in). Large print is also available on request either via the webpage or by calling 01480 277180. The consultation ends on 20th November.', -- description
  1, -- x_start
  10, -- y_start
  1, -- spanWidth
  9 -- spanHeight
);
 
-- 0150: Page 0001 item 03
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 1
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  3, -- order_by
  'I3', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'footer'), -- type_id
  'Front Cover Footer', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  '!! HAPPY HALLOWEEN FROM EVERYONE AT THE BAR HILL NEWS !!', -- description
  1, -- x_start
  20, -- y_start
  2, -- spanWidth
  1 -- spanHeight
);
 
-- 0150: Page 0002 item 01
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 2
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  1, -- order_by
  'I1', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Girlguide and Northstowe District', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'We believe Girls can do Anything!!!' || CHR(13) || 'Has your daughter just started a new year at school? Are they aged between 4 and 14 years old? Are they looking for new adventures? Would they like to take part in a fun programme of activities leaving them feeling challenged, inspired and empowered!?' || CHR(13) || 'Girlguiding is the largest organisation for girls and young women in the UK. In Bar Hill we have Rainbows, Brownies, Guides all offering an exciting, adventurous programme of activities.' || CHR(13) || 'The programme is designed for girls to:' || CHR(13) || '• Learn about themselves.' || CHR(13) || 'Find their voice, discover how to use it and feel empowered to do so.' || CHR(13) || 'Gain skills and confidence so that they know they can do anything.' || CHR(13) || '• a huge range of activities to try, plenty of badges to earn and loads of ways to develop new skills.' || CHR(13) || '• Designed and created with girls, our programme is packed full of fun, adventure and variety. And it supports girls to broaden their horizons, challenge themselves and be the best they can be.' || CHR(13) || 'Does this sound like something your daughter would enjoy? Why not come along for a taster visit?' || CHR(13) || 'For more information email barhillguiding@icloud.com or go to the girlguiding website https://www.girlguiding.org.uk/information-for-parents/register-a-child/', -- description
  0, -- x_start
  0, -- y_start
  2, -- spanWidth
  13 -- spanHeight
);
 
-- 0150: Page 0002 item 02
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 2
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  2, -- order_by
  'I2', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Bar Hill Indoor Bowls Club', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'We meet in the school on Friday evenings during term time only from 7.30 pm to 10pm with a 1/2 hour break for coffee. We are a very friendly group and we would love to have some new members. It doesn’t matter if you have never played before just come along and join us one Friday, the cost is £2 per week but the 1st week is free.' || CHR(13) || 'So why not come along and give it a try?' || CHR(13) || 'If you would like more information please contact me on 01954 204171 / 07847 327709 or barbara.page@live.co.uk', -- description
  0, -- x_start
  14, -- y_start
  1, -- spanWidth
  6 -- spanHeight
);
 
-- 0150: Page 0002 item 03
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 2
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  3, -- order_by
  'I3', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Wildlife Gardening in October', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Some ways you can support animals in October in your garden include;' || CHR(13) || '1. Leaving seeds, nuts, and water for birds.' || CHR(13) || '2. Piling logs, leaves, and compost to provide homes for insects, hedgehogs, etc.' || CHR(13) || '3. Clearing ponds of debris, but leave some for overwintering creatures like frogs and newts.' || CHR(13) || '4. Allowing plants to go to seed and leave stems standing for insects to shelter in.' || CHR(13) || 'These steps help wildlife survive the colder months.', -- description
  1, -- x_start
  14, -- y_start
  1, -- spanWidth
  6 -- spanHeight
);
 
-- 0150: Page 0003 item 01
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 3
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  1, -- order_by
  'I1', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Bar Hill Community Association', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Chair of Trustees	Andy Pellew' || CHR(13) || 'Vice Chair	Anthony Mitchell' || CHR(13) || 'Secretary	Jenni Foster-Smith' || CHR(13) || 'Treasurer/ BHN Advertising	Hilary Whipp' || CHR(13) || 'BHN Editor	Andy Pellew' || CHR(13) || 'Features Editors	"Liz Dams, and' || CHR(13) || 'Bridget Wilson"' || CHR(13) || 'Trustees' || CHR(13) || 'Bunty Waters	Jo Hall' || CHR(13) || 'Kate Da Costa	', -- description
  0, -- x_start
  0, -- y_start
  1, -- spanWidth
  9 -- spanHeight
);
 
-- 0150: Page 0003 item 02
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 3
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  2, -- order_by
  'I2', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Bar Hill Community Association Contact Information', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'If you’d like to contact the BHCA then you can either;' || CHR(13) || 'Write to us at Parish Council Offices, Hanover Close, Bar Hill. CB23 8EH' || CHR(13) || 'Email the Chair of Trustees at chair-of-trustees@barhill-ca.org, or' || CHR(13) || 'Call/ message/ WhatsApp 07814 871752.' || CHR(13) || 'We meet monthly on the second Tuesday at 7:30 pm in the Fox. If you’d like an agenda please get in touch!', -- description
  0, -- x_start
  10, -- y_start
  1, -- spanWidth
  6 -- spanHeight
);
 
-- 0150: Page 0003 item 03
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 3
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  3, -- order_by
  'I3', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Publishing disclaimer', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Opinions expressed in this publication are not necessarily those of the Association. Anonymous letters will not be published. Names and addresses may be withheld.' || CHR(13) || 'There is no charge for Articles, What’s On, For Sale or Lost and Found. These appear at the Editor’s discretion.' || CHR(13) || 'All items should be submitted to bhn-editor@barhill-ca.org', -- description
  0, -- x_start
  16, -- y_start
  1, -- spanWidth
  4 -- spanHeight
);
 
-- 0150: Page 0003 item 04
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 3
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  4, -- order_by
  'I4', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Bar Hill Community Association Url', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'See www.barhill-ca.org', -- description
  0, -- x_start
  20, -- y_start
  1, -- spanWidth
  1 -- spanHeight
);
 
-- 0150: Page 0003 item 05
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 3
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  5, -- order_by
  'I5', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Abeeton Plastering', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'summary'), -- description_type_id
  'An advert for Abeeton Plastering (Andrew Beeton)', -- description
  1, -- x_start
  0, -- y_start
  1, -- spanWidth
  10 -- spanHeight
);
 
-- 0150: Page 0003 item 05
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 3
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  5, -- order_by
  'I5', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'advert'), -- type_id
  'Michell Dolan Podiatrist/Chiropodist', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'summary'), -- description_type_id
  'An advert for Michell Dolan’s podiatrist and chiropody services.', -- description
  1, -- x_start
  0, -- y_start
  11, -- spanWidth
  10 -- spanHeight
);
 
-- 0150: Page 0004 item 01
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 4
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  1, -- order_by
  'I1', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'header'), -- type_id
  'Letters, Notices & Announcements To The Editor', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Please send your letters & notices to bhn-editor@barhill-ca.org. Thank you!', -- description
  1, -- x_start
  1, -- y_start
  2, -- spanWidth
  2 -- spanHeight
);
 
-- 0150: Page 0004 item 02
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 4
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  2, -- order_by
  'I2', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'footer'), -- type_id
  'Deadline information', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'The deadline for submissions is the second Thursday of the Month. Please send your article to bhn-editor@barhillca.org (PDF, Word, Pages, etc)', -- description
  1, -- x_start
  20, -- y_start
  2, -- spanWidth
  1 -- spanHeight
);
 
-- 0150: Page 0004 item 03
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 4
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  3, -- order_by
  'I3', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'reader content'), -- type_id
  'FOR SALE: On behalf of Happy Hours', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'FOR SALE: On behalf of Happy Hours 12 Popular Crafts magazines. Vol 18 no.3 (Feb 97) – Vol 19 no. 1 (Jan 98). £5' || CHR(13) || 'Golden Hands Encyclopaedia of Crafts (2nd edition).  Part 1 - 98, complete set EXCEPT for part 61 which is missing.  £15' || CHR(13) || 'Golden Hands: Knitting, Dressmaking and Needlecraft.  Part 1 – 30 EXCEPT for part 6 which is missing.  £5' || CHR(13) || 'Golden Hands: Knitting, Dressmaking and Needlecraft. Part 46 – 75.  £5' || CHR(13) || 'Contact email: anne@rwp10.plus.com or Tel: 01954780364 (answerphone)', -- description
  1, -- x_start
  3, -- y_start
  1, -- spanWidth
  6 -- spanHeight
);
 
-- 0150: Page 0004 item 04
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 4
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  4, -- order_by
  'I4', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'reader content'), -- type_id
  'Dear all', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Dear all,' || CHR(13) || 'It’s that time of the year again - Halloween - so it’s also time for our annual gentle reminder that some people, particularly vulnerable people and the elderly, will be struggling with “trick or treat”.' || CHR(13) || 'Parents can you please encourage your children to only call on decorated houses - people with halloween lights, pumpkins, etc - and NOT houses without them.' || CHR(13) || 'This way we can make this a safe and enjoyable time for everyone!' || CHR(13) || 'Yours sincerely,' || CHR(13) || 'Andy Pellew' || CHR(13) || 'Bar Hill News Editor | 07814 871 752', -- description
  1, -- x_start
  9, -- y_start
  1, -- spanWidth
  7 -- spanHeight
);
 
-- 0150: Page 0004 item 05
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 4
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  5, -- order_by
  'I5', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'reader content'), -- type_id
  'Dear residents', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Dear Residents, ' || CHR(13) || 'Thank you to the 80 people who braved the rain to support the ICB(NHS) Public Meeting in September.  A good turnout, representing all local surgeries, ensured that the ICB recognised local concerns.' || CHR(13) || 'Ms Jan Thomas (CEO Cambs&Pboro ICB) apologised to patients of Maple Surgery for the many changes of provider in recent years.  While having to adhere to legal processes, she acknowledged the ICB had failed to communicate with patients about the recent tendering process.' || CHR(13) || 'The impact on all local surgeries of no GP provision in Northstowe until 2028, was discussed.  Ms Thomas offered to return next year and report on how plans are progressing.' || CHR(13) || 'Pam Vendy | Secretary | Maple PPG', -- description
  2, -- x_start
  3, -- y_start
  1, -- spanWidth
  9 -- spanHeight
);
 
-- 0150: Page 0004 item 06
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 4
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  6, -- order_by
  'I6', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'reader content'), -- type_id
  'Dear residents', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Dear Residents,' || CHR(13) || 'The Annual General Meeting of the Bar Hill Allotment Society is being held on Friday 11th October in the Octagon at 7.30pm.' || CHR(13) || 'If you are interested in allotmenteering and want to find out more, you are very welcome to attend. You can also contact us at barhillallotment@gmail.com' || CHR(13) || 'Maggie Annat | Chairperson BHAS', -- description
  2, -- x_start
  12, -- y_start
  1, -- spanWidth
  4 -- spanHeight
);
 
-- 0150: Page 0004 item 07
INSERT INTO tmap_v0.page_item(page_id, order_by, key, type_id, title, description_type_id, description, x_start, y_start, spanWidth, spanHeight)
VALUES (
  (SELECT p.id
  FROM tmap_v0.page p
  JOIN tmap_v0.issue i ON i.id = p.issue_id
  WHERE p.page_number = 4
  AND i.name = 'Bar Hill News 202410 October 2024 Issue 661'), -- page_id
  7, -- order_by
  'I7', -- key
  (SELECT pit.id FROM tmap_v0.page_item_type pit WHERE name = 'article'), -- type_id
  'Coffee, Cake & Conversation - Wednesday 9th October at 4 pm', -- title
  (SELECT id FROM tmap_v0.description_type WHERE name = 'exact'), -- description_type_id
  'Coffee, Cake & Conversation - Wednesday 9th October at 4 pm' || CHR(13) || 'For Libraries Green Week, we are asking our community what would you like to see from Bar Hill Library?' || CHR(13) || 'Is there a special talent or group you would like to set up? Or would you just like another informal community space to meet new people? Come and tell us, enjoying some afternoon refreshment and cake. Free to come and everyone is welcome!', -- description
  1, -- x_start
  16, -- y_start
  2, -- spanWidth
  4 -- spanHeight
);
